---
title: "p8105_hw2_yo2336"
author: "Yoo Rim Oh"
output: github_document
---
```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
```

# Problem 1

Read Mr.Trash excel data and name data frame as trash_df
```{r}
trash_df = 
  read_excel("data/trash_wheel.xlsx", sheet = "Mr. Trash Wheel") %>%
  janitor::clean_names() %>%
  select(-"month", -"year", -"date", -"x15", -"x16", -"x17") %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = as.integer(sports_balls))
```


Precipitation Data
```{r}
precip_df_2018 =
  read_excel("data/trash_wheel.xlsx", sheet = "2018 Precipitation", skip = 1) %>%
  janitor::clean_names() %>%
  rename(precipitation_in = total) %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)


precip_df_2019 =
  read_excel("data/trash_wheel.xlsx", sheet = "2019 Precipitation", skip = 1) %>%
  janitor::clean_names() %>%
  rename(precipitation_in = total) %>%
  drop_na(month, precipitation_in) %>%
  mutate(year = 2019) %>%
  relocate(year)


precip_df =
  bind_rows(precip_df_2018, precip_df_2019) %>%
  janitor::clean_names() %>%
  mutate(month = month.name[as.numeric(month)])
```

Precipitation Data Description
```{r}

```


# Problem 2


Part 1 Clean pols-month.csv
```{r}
pols_month_df =
  read_csv("data/fivethirtyeight_datasets/pols_month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day")) %>%
  mutate(month = month.name[as.numeric(month)]) %>%
  relocate(year, month, prez_gop, prez_dem) %>%
  rename(gop = prez_gop, dem = prez_dem) %>%
  pivot_longer(
    gop:dem,
    names_to = "president",
    values_to = "prez_numeric") %>%
  filter(prez_numeric == 1) %>%
  select(-c("prez_numeric", "day")) %>%
  relocate(year, month, president)
```

Part 2 Clean snp.csv

```{r}
snp_df =
  read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  mutate(date = lubridate::mdy(date)) %>%
  separate(date, into = c("year", "month", "day")) %>%
  arrange(year, month) %>%
  mutate(month = month.name[as.numeric(month)]) %>%
  select(-"day")
```

Part 3 Clean unemployment.csv and merge

```{r}
unemp_df =
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent_unemployment")
```

Join snp and pols data

```{r}
snp_pols_df =
  full_join(snp_df, pols_month_df) %>%
  mutate(year = as.numeric(year))
```

Join combined snp_pols with unemployment

```{r}
snp_pols_unemp_df =
  left_join(snp_pols_df, unemp_df, by = "year")
```

Description


# Problem 3

```{r}
baby_name_df =
  read_csv("data/Popular_Baby_Names.csv") %>%
  janitor::clean_names() %>%
  unique() %>%
  relocate(year_of_birth, rank, childs_first_name) %>%
  arrange(year_of_birth, ethnicity)
  
```

